### ISSUE TITLE
Thermal Expansion Caches

### ISSUE THREAD

**Issue by ChatFawkes** [tterrag1098/WAILAPlugins#20]
It would be nice to be able to know the exact amount of items in a cache in WAILA because it doesn't have a GUI (only a bar to show how full it is).

**Comment by BionicFelps** [comment]
Seconded, would increase the usefulness of caches to show A) what's in them (a lot of dusts look similar), and B) how much without having to use a multimeter on them.

**Comment by tterrag1098** [comment]
I personally think the caches are already quite overpowered for a barrel-esque block, they hold way more for way less than JABBA or FZ. I don't really want to buff them.

**Comment by ChatFawkes** [comment]
Closing this because it was added directly to WAILA.
