### ISSUE TITLE
Magic Crop Crash

### ISSUE THREAD

**Issue by MrSapient** [tterrag1098/WAILAPlugins#24]
Crashes on start up.

http://pastebin.com/5pxe7R5V

**Comment by tterrag1098** [comment]
The unreleased magical crops version is not yet supported. Either downgrade
or disable that plugin in the config.

**Comment by MrSapient** [comment]
didnt know it was unreleased .. i got it from sky factory 2 public pack.

**Comment by tterrag1098** [comment]
The release is not anywhere online that I can see (other than mod packs)
and I can only support one version.

**Comment by tterrag1098** [comment]
Latest build updated to use magical crops 4.0 beta
