### ISSUE TITLE
Extra config tab

### ISSUE THREAD

**Issue by Adaptivity** [tterrag1098/WAILAPlugins#27]
This tab -> http://i.imgur.com/d2YAY8J.jpg completely empty. Is there is any reason why it is exist?

P.S if it is an issue, you also might want to fix "authors" -> "authorList" in mcmod.info.

**Comment by tterrag1098** [comment]
It doesn't exist anymore, it's from an old version. You can delete it from the WAILA configuration file.

**Comment by Adaptivity** [comment]
I deleted wailaplugins.cfg. It generated again but this tab still exist even on newly created world.

**Comment by tterrag1098** [comment]
No I mean the WAILA.cfg

**Comment by Adaptivity** [comment]
I tried and nope, this tab still exist.

**Comment by tterrag1098** [comment]
Oh yeah...oops. Fixed now.
