### ISSUE TITLE
Current bees inside apiaries

### ISSUE THREAD

**Issue by quienti** [tterrag1098/WAILAPlugins#28]
I can't see current bees inside apiaries :(

![2015-02-26_15 56 48](https://cloud.githubusercontent.com/assets/7326954/6394546/81765ce4-bdd2-11e4-9a34-1813e0837caf.png)
![2015-02-26_15 56 54](https://cloud.githubusercontent.com/assets/7326954/6394547/81f84de4-bdd2-11e4-81cf-8beae10c7130.png)

Forestry : 3.5.0.473
Waila : 1.5.9
Waila Plugins : 0.0.1.13
ttCore : 0.1.0-67

**Comment by tterrag1098** [comment]
Is this only happening after a forestry update?

**Comment by quienti** [comment]
Oh no ! For me, a long time ago, I never see bees in my apiary ^^

**Comment by tterrag1098** [comment]
Fixed via http://git.io/hiqb
