### ISSUE TITLE
Crash with Mekanism's new v8 release

### ISSUE THREAD

**Issue by seanwcom** [tterrag1098/WAILAPlugins#29]
I believe I'm reading the crash report correctly, I apologize if I'm not. This is in a custom "kitchen sink" pack, but I recently added Mek v8 to my test world to see what's new. 

The error: java.lang.ClassNotFoundException: mekanism.common.tile.TileEntitySalinationController

And that's not so helpful without the crash Log: http://paste.ee/p/GAxvf

Thanks!

**Comment by Xee1** [comment]
I can confirm this @tterrag1098

**Comment by bochen415** [comment]
Mekanism=false in the config file (temporary solution)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/WAILAPlugins/commit/7db7beb3a42aac9bb2378db28908cf853d897cb7

**Comment by Xee1** [comment]
Thanks tterrag!
