### ISSUE TITLE
Support request: MineFactory Reloaded

### ISSUE THREAD

**Issue by MrBretze** [tterrag1098/WAILAPlugins#31]
add the worck in machin ?

**Comment by Keridos** [comment]
Yeah please add support for it, I would love to see the content of DeepStorageUnits when I view them.

**Comment by tterrag1098** [comment]
![](http://puu.sh/hxxev.jpg)

![](http://puu.sh/hxxSv.jpg)

Look good?

**Comment by MrBretze** [comment]
Y like this :)

**Comment by tterrag1098** [comment]
I will probably split off the IDeepStorageUnit handler from the MFR plugin so that it works with other mods, such as JABBA and TE.

**Comment by MrBretze** [comment]
JABBA and waila is comptaible no ?

**Comment by tterrag1098** [comment]
I don't think it shows barrel contents in WAILA, but I could be wrong.

**Comment by Keridos** [comment]
yay @tterrag1098 looks good

**Comment by Simon04090** [comment]
JABBA definitely has WAILA support. It has the same author (ProfMobius). I think it was one of the first mods he added support for
