### ISSUE TITLE
ExU Drums: contents not visible in MP, WP r14

### ISSUE THREAD

**Issue by Barhandar** [tterrag1098/WAILAPlugins#32]
ExU version is 1.2.1 (host refuses to update - 1.2.4's required Forge crashes MC on load). In singleplayer it shows correctly ("water drum, 1000/256,000 mB"), multiplayer, no dice. In WP r13 it was showing in both.

**Comment by tterrag1098** [comment]
What WAILA version?

**Comment by Barhandar** [comment]
WAILA 1.5.9, hadn't been updated. Other WP functions (Blood Magic's altar info, Flaxbeard's Steam gauge info) work fine.

**Comment by tterrag1098** [comment]
Which is odd because they all use the same code, more or less.

**Comment by Barhandar** [comment]
Which is why I've considered it really strange. I'm trying to persuade the host to put WP on server, maybe it will result in drum values showing again.

**Comment by tterrag1098** [comment]
Wait, WAILAPlugins is not on the server? That is not allowed, it won't work properly without serverside data.
