### ISSUE TITLE
ClassNotFoundException when server starts

### ISSUE THREAD

**Issue by ams2990** [tterrag1098/WAILAPlugins#33]
If I have only ttCore and Waila in my mods folder, the server starts fine with no errors. If I add WAILAPlugins, I get an IllegalStateException caused by a ClassNotFoundException. I suspect it has something to do with the mod load order but am not sure. The full error is here: http://pastebin.com/raw.php?i=1qT7zxcm

I am running Cauldron 1343, and have ttCore 0.1.0.67, Waila 1.5.10, and WAILAPlugins 0.0.1-14.

**Comment by tterrag1098** [comment]
That's a harmless error.

**Comment by ams2990** [comment]
Regardless, can you move the reference to a class that is not loaded unless the base class exists? Logspam is, as a rule, bad since it makes it harder to identify genuine issues.
