### ISSUE TITLE
How to Remove WAILA mobs

### ISSUE THREAD

**Issue by lightning02** [tterrag1098/WAILAPlugins#34]
I have a question, do you know how to delete WAILA for mobs and entities as to leave Damage indicators only for mobs?
i changed the parameter : B:general.showhp=true in false but it removed only the hp of mobs but not their names, just like this http://i.imgur.com/lEki5Vu.jpg 
i would like to leave only the left name of mobs! :)

**Comment by tterrag1098** [comment]
I don't think that's possible, it would be good to suggest it to ProfMobius here: https://bitbucket.org/ProfMobius/waila/issues?status=new&status=open
