### ISSUE TITLE
Magical Crops => Growth-Status 

### ISSUE THREAD

**Issue by ReneMuetti** [tterrag1098/WAILAPlugins#36]
Hello

There appears no progress bar. It is only the MOD and the name will be displayed, but not how far is the growth.

Thank you

**Comment by tterrag1098** [comment]
What? Screenshots? What mod version? What magical crops version?

**Comment by ReneMuetti** [comment]
MagicalCrops 4.0.0 BETA 3
Waila 1.5.10
Waila Harvestability 1.1.2
WAILA Plugins 0.0.1-15

Screens:
http://www.info-panel.net/mc/2015-05-26_18.44.22.png
http://www.info-panel.net/mc/2015-05-26_18.44.27.png

**Comment by tterrag1098** [comment]
Magical Crops 4.0 is not supported. See #24

**Comment by ReneMuetti** [comment]
Hello

Thanks for the information. I have now installed the version 1.7.10-0.1. To make it work. Will there be an update to the new version?

**Comment by tterrag1098** [comment]
When it's fully released, yes.
