### ISSUE TITLE
Railcraft Tank Support

### ISSUE THREAD

**Issue by Timeslice42** [tterrag1098/WAILAPlugins#38]
Now that @CovertJaguar has released the version of RC which fixes the contents of tanks not properly synching with the client, the WAILA tooltip no longer shows the correct information. It just displays 0/X all of the time. I'm guessing he renamed the field/property? Either way, it doesn't work.

**Comment by Timeslice42** [comment]
I don't know if you have a bitbucket account, but you may want to comment here if/when you fix this: https://bitbucket.org/ProfMobius/waila/issue/192/waila-and-railcraft

**Comment by tterrag1098** [comment]
Will investigate soon

**Comment by tterrag1098** [comment]
What type of tank has the issue? WAILA has a built-in plugin for railcraft iron tanks, I add almost everything else.

**Comment by tterrag1098** [comment]
and from here it seems to be working fine:

![](http://puu.sh/iIFvv.png)

**Comment by Timeslice42** [comment]
Iron/steel tanks. The current amount and the fluid name are not displayed correctly.

**Comment by tterrag1098** [comment]
Right. That's not me. Report to WAILA.

**Comment by Timeslice42** [comment]
Is @ProfMobius even still around?

**Comment by tterrag1098** [comment]
He was just on the panel at minecon, I think he is yes.
