### ISSUE TITLE
WAILAPlugins switch to Endercore

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [tterrag1098/WAILAPlugins#40]
Please, I can has wailaplugins with endercore?

**Comment by spannerman79** [comment]
+1
RedstoneArmory has moved to EnderCore, making ttCore depend an issue (neither can be run together)

**Comment by tterrag1098** [comment]
Doing this for every mod I own will take time, and I will do it when I have time.

**Comment by spannerman79** [comment]
:ok_hand:

**Comment by tterrag1098** [comment]
Fixed in 0.1.0
