### ISSUE TITLE
Where can I download EnderCore 1.7.10 - 0.0.1.8 alpha?

### ISSUE THREAD

**Issue by Tsyklop** [tterrag1098/WAILAPlugins#42]
![default](https://cloud.githubusercontent.com/assets/6783568/8448419/e7c7693e-1fcf-11e5-9aa6-440709546edb.png)

Here http://minecraft.curseforge.com/mc-mods/231868-endercore/files -  1.7.10. - 0.0.1.4 alpha

**Comment by tterrag1098** [comment]
I need to put a new version on curse. Until then, [use this link](http://ci.tterrag.com/job/EnderCore).

**Comment by Tsyklop** [comment]
@tterrag1098 thx.
