### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Tsyklop** [tterrag1098/WAILAPlugins#43]
Crash EnderCore-1.7.10-0.0.1.10_alpha

http://pastebin.com/3gZKiUWJ

	UCE	endercore{1.7.10-0.0.1.10_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.10_alpha.jar) 
	UCE	NEM-VersionChecker{0.1} [NEM Version Checker] (NEM-VersionChecker-1.7.10-1.0.jar) 
	UCE	wailaplugins{MC1.7.10-0.1.0-16} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.0-16.jar)

And I have a question. Now I can remove ttCore?

**Comment by tterrag1098** [comment]
If you have no other mods which require it, yes.

**Comment by Tsyklop** [comment]
@tterrag1098 Ok.what about Crash?

**Comment by tterrag1098** [comment]
This crash is in dynamiclights code, I have no idea how endercore or any of my mods could cause it.
