### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [tterrag1098/WAILAPlugins#47]
Waila Plugins: MC1.7.10-0.0.1-16
Forge: 1448
Crash Report: http://pastebin.com/3RJnAFSf

**Comment by tterrag1098** [comment]
This crash occurs in MapWriter code

**Comment by Xiaminou** [comment]
Yeah but it does AFTER I have updated YOUR mod.

**Comment by tterrag1098** [comment]
Report it to them still, I can't read mapwriter code so I can't know the cause.
