### ISSUE TITLE
Forestry Leaves show it's own tree and not it's mate when polinated

### ISSUE THREAD

**Issue by wmrojer** [tterrag1098/WAILAPlugins#50]
Whatever I polinate a Silver Birch leave with it will always show "Polinated with: Silver Birch" instead of what it is acutally polinated with (mate). It's the same for all types of leaves, they just show there own spieces instead of that of the mate.

**Comment by tterrag1098** [comment]
Forestry API has changed a bit, I may need to update my methods.

**Comment by tterrag1098** [comment]
Ok I found the issue, Forestry has changed how leaves store clientside data, so I will need to grab the breeding data from the server instead of the client. Easy fix :)

**Comment by tterrag1098** [comment]
This is fixed in 0.1.1
