### ISSUE TITLE
Railcraft tank

### ISSUE THREAD

**Issue by MrSapient** [tterrag1098/WAILAPlugins#51]
Tank has over 100k buckets of Creosote oil ..

Steel tank 5x5x6
http://i.imgur.com/s7tQStt.png
WAILAPlugins - 0.1.2-18
Railcraft - 7.0
Forge - 10.13.4.1492

**Comment by tterrag1098** [comment]
https://twitter.com/tterrag1098/status/633332716189155328

**Comment by tterrag1098** [comment]
Fixed in 8df1aa412ff08c48949639eede3b9485092319f2
