### ISSUE TITLE
Magical Crops plugin

### ISSUE THREAD

**Issue by xJon** [tterrag1098/WAILAPlugins#52]
It's not working with the latest versions of WAILAPlugins.
![image](https://cloud.githubusercontent.com/assets/8945347/9468282/752d28be-4b49-11e5-96be-8f0652e823f6.png)
Using Magical Crops (release) v1.7.10_0.1
Worth to mention that I also found [this](http://pastebin.com/V6B74NTy) in the fml-client-latest.log file.

**Comment by tterrag1098** [comment]
I can only support one version of Magical Crops and right now that is the 4.0 BETA version.

**Comment by xJon** [comment]
Alright, I figured that that's the case, it's just that I didn't see any thing in the changelogs. Maybe I missed it.
Thanks for the reply!
