### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xen1290** [tterrag1098/WAILAPlugins#55]
https://gist.github.com/Xen1290/0293eb1d624cffcd8207

forestry_1.7.10-4.0.0.688-unstable
Waila-1.5.10_1.7.10
WAILAPlugins-MC1.7.10-0.1.2-21
@tterrag1098

**Comment by tterrag1098** [comment]
I do not support forestry 4.0, it is far too different. Once it is released I will update the support.

**Comment by Xen1290** [comment]
Oh sorry, thanks!
