### ISSUE TITLE
Update to forestry 4.0.7 stable

### ISSUE THREAD

**Issue by Xen1290** [tterrag1098/WAILAPlugins#60]
Hi @tterrag1098 , Forestry 4.x stable is out, maybe you can fix support for that version? Related to:
https://github.com/tterrag1098/WAILAPlugins/issues/55

**Comment by tterrag1098** [comment]
Yes, as soon as I find some time I will update.

**Comment by Xen1290** [comment]
Thanks!

**Comment by Xen1290** [comment]
Thanks!
