### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xen1290** [tterrag1098/WAILAPlugins#61]
@tterrag1098 
https://gist.github.com/Xen1290/940d2544375696cbb786
Latest version from courseforge for Forestry and WAILA Plugins.

**Comment by tterrag1098** [comment]
Waiting on mezz to release forestry 4.1 so that I can release.

**Comment by Xen1290** [comment]
Perfect, thanks!

**Comment by Xen1290** [comment]
Forestry 4.1.0 is now out

**Comment by Xen1290** [comment]
Fixed
