### ISSUE TITLE
Mekanism V9 API updates

### ISSUE THREAD

**Issue by NEXUS2345** [tterrag1098/WAILAPlugins#64]
WAILA Plugins currently cannot load the Mekanism support due to the following error:

https://gist.github.com/NEXUS2345/d71eedcbd96b7109555caaae6b3d3a12

**Comment by spannerman79** [comment]
Also reported via https://github.com/aidancbrady/Mekanism/issues/3482

**Comment by clienthax** [comment]
https://github.com/tterrag1098/WAILAPlugins/pull/66
