### ISSUE TITLE
Latest build failing.

### ISSUE THREAD

**Issue by EntityReborn** [tterrag1098/WAILAPlugins#69]
Title pretty much says it all. Interested in this, as WAILA alone doesn't know what Mekanism block you are looking at, and can't see contents of blocks.

**Comment by tterrag1098** [comment]
Failing how? Do you have a log?

**Comment by EntityReborn** [comment]
Failing on your Jenkins.

**Comment by tterrag1098** [comment]
Wow, I see. Should be a new build up soon.

**Comment by EntityReborn** [comment]
Any possibility of getting a version bump as well? =D

**Comment by EntityReborn** [comment]
It is also worth noting that the last build has been running for over an hour now.

**Comment by tterrag1098** [comment]
Should be done now. Sorry about that.
